### ISSUE TITLE
Qemu submodule pixman ? 

### ISSUE THREAD

**Issue by l4es** [k0nze/qemu_zynq_linux_setup#1]
Hello,

I'm new to Xilinx Petalinux and I'm following your repo trying to run it on Qemu. But from the README, I find there's no pixman submodule in qemu repo. Am I wrong?

Thanks and best regards,
Khang

**Comment by k0nze** [comment]
Since this setup guide is pretty old (3 years) now the QEMU repo has changed. Those steps have been performed on commit `0748b3526e8cb78b9cd64208426bfc3d54a72b04` of the QEMU repo.

**Comment by l4es** [comment]
Thanks for your support
